version: '3.8'

services:
#  db:
#    platform: linux/amd64
#    image: mysql:5.7.36
#    container_name: mysql
#    restart: always
#    ports:
#      - "3306:3306"
#    volumes:
#      - db-data:/var/lib/mysql
#    environment:
#      MYSQL_DATABASE: 'mysql'
#      MYSQL_USER: 'guests'
#      MYSQL_PASSWORD: MYSQL_PASSWORD
#      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
#
#    env_file: .env
#    tty: true
#    stdin_open: true

  web:
    platform: linux/amd64
    build: .
    ports:
      - '8888:8888'

    # mount先指定
    volumes:
      - '.:/work'

    tty: true
    stdin_open: true

#    depends_on:
#      - db
#    links:
#      - db

#volumes:
#  db-data:
