version: '3.8'

services:
  mariadb:
    image: mariadb:10.5.9
    container_name: mariadb
    restart: always
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'mariadb'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    env_file: .env
    tty: true
    stdin_open: true

  web:
    platform: linux/amd64
    build: .
    ports:
      - '8888:8888'

    # mount先指定
    volumes:
      - '.:/work'

    tty: true
    stdin_open: true

    depends_on:
      - mariadb
    links:
      - mariadb

volumes:
  db-data: