version: '3.8'

services:
  mariadb:
    image: mariadb:10.4.6
    container_name: mariadb
    env_file: .env
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'mariadb'
      MYSQL_ROOT_PASSWORD: "PassWord00"
      TZ: Asia/Tokyo
    tty: true
    stdin_open: true

  web:
    platform: linux/amd64
    build: .
    ports:
      - '8888:8888'

    # mount先指定
    volumes:
      - '.:/work'

    tty: true
    stdin_open: true

    depends_on:
      - mariadb
    links:
      - mariadb

volumes:
  db-data:
